# Generated by Django 6.0.6 on 2026-07-05 14:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='cloudinary_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='room_icon'),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media_file'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
    ]
