# Generated by Django 6.0.6 on 2026-07-05 14:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pics/default.png', max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
